### ISSUE TITLE
Update SMR for new anki versions please!!!

### ISSUE THREAD

**Issue by sogardoliver** [Humorloos/SMR#13]
It would be awesome if you could update the add on for newer anki versions!

**Comment by Humorloos** [comment]
Hi sogardoliver, thanks for your interest in this add on. I'm sorry to tell you that since this was a personal project of mine that I wrote primarily for my own studies, and since I currently don't really need it (especially not for new anki versions) I won't be working on it anytime soon. However, I'm still interested in this topic in general, so if there is interest by more people in the future, I may pick it up again.

**Comment by sogardoliver** [comment]
Would it work to talk about potentially working on this via email? We have a few people in my class that would be interested in paying for your work on the project if possible!

**Comment by Humorloos** [comment]
You can write a message in my discord channel: https://discord.gg/faerEmSZ

**Comment by Humorloos** [comment]
Development will now be tracked in issue #14
